DROP TABLE IF EXISTS AMIZADE CASCADE;
DROP TABLE IF EXISTS COMPRA CASCADE;
DROP TABLE IF EXISTS JOGADOR_CRACHA CASCADE;
DROP TABLE IF EXISTS JOGADOR_STATS CASCADE;
DROP TABLE IF EXISTS MENSAGEM CASCADE;
DROP TABLE IF EXISTS Partida_MULTIJOGADOR CASCADE;
DROP TABLE IF EXISTS Pontuacao_MULTIJOGADOR CASCADE;
DROP TABLE IF EXISTS Partida_NORMAL CASCADE;
DROP TABLE IF EXISTS PARTIDAS CASCADE;
DROP TABLE IF EXISTS REGIAO CASCADE;
DROP TABLE IF EXISTS JOGADORES CASCADE;
DROP TABLE IF EXISTS JOGO CASCADE;
DROP TABLE IF EXISTS JOGO_STATS CASCADE;
DROP TABLE IF EXISTS CONVERSA CASCADE;
DROP TABLE IF EXISTS CRACHA CASCADE;
drop type if exists joga_states CASCADE;
drop type if EXISTS multi_states CASCADE;
DROP FUNCTION if exists totalpontosjogador(integer) CASCADE;
DROP Procedure if exists iniciar_conversa(integer,character varying)CASCADE;
DROP PROCEDURE IF EXISTS associarCracha(integer,character varying,character varying) CASCADE;
DROP PROCEDURE IF EXISTS enviarMensagem(INTEGEr, INTEGER,TEXT)CASCADE;
DROP PROCEDURE IF EXISTS juntarConversa(INTEGEr, INTEGER)CASCADE;
drop procedure if exists totalPontosJogador(integer)CASCADE;
DROP VIEW IF EXISTS jogadorTotalInfo CASCADE;


